services:

  postgres:
    image: postgres:17.4
    container_name: taskmanager_postgres
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"


  api:
    build: .
    container_name: taskmanager_api
    restart: unless-stopped

    depends_on:
      - postgres

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/taskmanager

volumes:
  postgres_data: